import 'dart:convert';
import 'package:http/http.dart';

const GOOGLE_API_KEY = 'AIzaSyAipVwKQ0qSoD6FOv3sBDKDVXivCf2M5og';

class LocationHelper {
  static String generateLocationPreviewImage({
    double latitude,
    double longitude,
  }) {
    // return a url of the image dynamically generated by google
    // base on the pair of co-ordinates
    return 'https://maps.googleapis.com/maps/api/staticmap?center=$latitude,$longitude&zoom=13&size=600x300&maptype=roadmap&markers=color:red%7Clabel:C%7C$latitude,$longitude&key=$GOOGLE_API_KEY';
  }

  static Future<String> getPlaceAddress(double lat, double lng) async {
    final url =
        'https://maps.googleapis.com/maps/api/geocode/json?latlng=$lat,$lng&key=$GOOGLE_API_KEY';
    final response = await get(url);
    // the response will contain the data we need in json
    return json.decode(response.body)['results'][0]['formatted_address']; // return the place's address
  }
}
